# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20170223_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentprof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('comprescore', models.IntegerField(blank=True, null=True)),
                ('wordreadingscore', models.IntegerField(blank=True, null=True)),
                ('spellingscore', models.IntegerField(blank=True, null=True)),
                ('creative', models.IntegerField(blank=True, null=True)),
                ('punctuation', models.IntegerField(blank=True, null=True)),
                ('composition', models.IntegerField(blank=True, null=True)),
                ('handwriting', models.FileField(blank=True, null=True, upload_to=b'')),
                ('handwritingscore', models.IntegerField(blank=True, null=True)),
                ('dr', models.IntegerField(blank=True, null=True)),
                ('ds', models.IntegerField(blank=True, null=True)),
                ('dh', models.IntegerField(blank=True, null=True)),
                ('dwe', models.IntegerField(blank=True, null=True)),
                ('dba', models.IntegerField(blank=True, null=True)),
                ('dha', models.IntegerField(blank=True, null=True)),
                ('da', models.IntegerField(blank=True, null=True)),
                ('ed', models.IntegerField(blank=True, null=True)),
                ('dm', models.IntegerField(blank=True, null=True)),
                ('lm', models.IntegerField(blank=True, null=True)),
                ('dss', models.IntegerField(blank=True, null=True)),
                ('dns', models.IntegerField(blank=True, null=True)),
                ('dll', models.IntegerField(blank=True, null=True)),
                ('dls', models.IntegerField(blank=True, null=True)),
                ('stl', models.IntegerField(blank=True, null=True)),
                ('rg', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
