# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_document_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='username',
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.ImageField(upload_to=b'Documents/%Y/%m/%d'),
        ),
    ]
