# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_studentprof_std'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprof',
            old_name='spellingscore',
            new_name='Spelling',
        ),
    ]
