# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20170314_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(blank=True, null=True)),
                ('subject_grade', models.IntegerField(blank=True, null=True)),
                ('res_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
